[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

gas_reports_ignore = ["Freeloader", "SelfRepayingENSStub", "ToolboxLocal"]

fs_permissions = [
    { access = "read", path = "./deployments/external.json" },
    { access = "read", path = "./broadcast/" }
]
