#+title: Self Repaying ENS
#+author: Wary

An Alchemix user can subscribe to the Self Repaying ENS Renewals service to automatically renew an expired ENS name. The renewal fee is paid by adding some self repaying debt to the user Alchemix account ðŸ§™ðŸª„ðŸ’¸. It was made for [[https://gitcoin.co/hackathon/moneylegos][Gitcoin's Money Legos Hackaton]].


* ðŸŒ Overview

The Self Repaying ENS Renewals is a smart contract written in Solidity that uses:
- the [[https://alchemix.fi/][Alchemix Protocol]] to manage users self repaying debt
- the [[https://ens.domains/][Ethereum Name System]] to manage the ENS names
- the [[https://www.gelato.network/][Gelato Network]] to automate the smart contract actions


* ðŸ§ How to use

âš  Prerequisites:
- Register a ENS name
- Deposit enough funds to the =alETH= AlchemistV2 contract

1. Allow the =SelfRepayingENS= contract (aka SRENS) to mint enough =alETH= debt to cover multiple renewals
2. Subscribe to the =SRENS= service for this name

Voila ! ðŸ¥³
That's it for the user actions.

This is where the automated actions starts
- Subscribing to the service for this name tells the =Gelato Network= to monitor regularly its expiry
- Once it expires, =Gelato= tells =SRENS= to renew it
- To renew it, =SRENS= mint enough =alETH= debt to pay for the renewal and =Gelato= fees in ETH


* ðŸšš How to install

âš  Prerequisites:
- [[https://git-scm.com/downloads][git]]
- [[https://book.getfoundry.sh/getting-started/installation][foundry]]

Clone this repository and install the dependencies
#+begin_src bash
git clone git@github.com:The-Wary-One/self-repaying-ens.git
mkdir self-repaying-ens
forge install
#+end_src


* ðŸ‘· How to test

The tests needs to be run in a Mainnet fork.
Set the environment variables with your API keys
#+begin_src bash
cat .env.example > .env
vim .env
#+end_src

Run the tests
#+begin_src bash
forge test
#+end_src


* ðŸƒ How to run locally

Set the environment variables with your API keys
#+begin_src bash
cat .env.example > .env
vim .env
#+end_src

Start [[https://book.getfoundry.sh/anvil/][anvil]] as a Mainnet fork using the custom task
#+begin_src bash
./tasks/start-fork-local.sh
#+end_src

Run the custom deploy task
#+begin_src bash
./tasks/deploy-local.sh
#+end_src

The deployed contract address is printed in the task logs.

Check if the contract is ready to be used by looking at the return values of this task
#+begin_src bash
./tasks/check-deploy-local.sh
#+end_src


