name: test

on:
  push:
    branches:
      - "main"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
          BLOCK_NUMBER_MAINNET: 15962250
        run: |
          forge test -vvv
        id: test
